version: '3'

services:

  db:
    image: postgres:13.3-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /home/ubuntu/postgres/data
      POSTGRES_INITDB_ARGS: "-A md5"
    ports:
      - "5432:5432"
    env_file:
      - .env

  django:
    build: .
    command: /docker-entrypoint.sh python manage.py runserver 0.0.0.0:8088
    volumes:
      - .:/source
    ports:
      - '8088:8088'
    depends_on:
      - db
    env_file:
      - .env
    restart: on-failure






