version: '3.12'

services:

  db:
    image: postgres:13.3-alpine
    container_name: my_car
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /home/ubuntu/postgres/data
      POSTGRES_INITDB_ARGS: "-A md5"
    ports:
      - "5433:5432"
    env_file:
      - .env






