version: '3.12'

services:

  db:
    image: postgres:13.3-alpine
    container_name: my_car
    restart: always
    environment:
      POSTGRES_PASSWORD: 898989
      POSTGRES_USER: tester
      POSTGRES_DB: my_car
      PGDATA: /home/ubuntu/postgres/data
      POSTGRES_INITDB_ARGS: "-A md5"
    ports:
    - "5433:5432"






