# Generated by Django 5.0.4 on 2024-05-02 15:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b4c9fcee-a75c-4bdf-ac3e-e16067755d76"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
