# Generated by Django 5.0.4 on 2024-04-24 13:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("bf37a6e7-0e13-40fd-8cc6-12518d011d5a"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
