# Generated by Django 5.0.4 on 2024-04-18 15:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("aa7a1fb3-5eb5-486c-a891-ee50d56f5a9d"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
