# Generated by Django 5.0.4 on 2024-04-30 10:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_alter_cars_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("4f37ab1f-952f-412d-a0d8-fac654415c12"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
