# Generated by Django 5.0.4 on 2024-05-02 15:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_alter_cars_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("8900f2b6-aa04-47ee-a224-72050360d20d"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
