# Generated by Django 5.0.4 on 2024-05-02 15:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_alter_cars_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("3599a74d-3ec7-4e22-a739-8f77f15f91c6"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
